x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.139.0
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    environment:
      - VALIDATOR_SECP=${VALIDATOR_SECP}
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
      - "4318:4318"   # OTLP HTTP receiver
    labels:
      - traefik.enable=false
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8889
      - metrics.instance=monad-otel-collector
      - metrics.network=monad
    <<: *logging

networks:
  default:
    name: ${DOCKER_EXT_NETWORK:-traefik_default}
    external: true
